### ISSUE TITLE
Pages appearing unstyled

### ISSUE THREAD

**Issue by srikat** [fadlee/oxygen-repeater-fix#1]
With the plugin active, required CSS seems to be missing from pages on the front end.

![screenshot](https://d.pr/i/DK71gY+)

**Comment by fadlee** [comment]
Can you explain more detail about your setup?

**Comment by srikat** [comment]
I have just tested this on the default Atomic design set install at http://oxygenbuilder.com/try.

Activated the plugin and elements in the header and some others appear unstyled.

The problem can be seen at http://clever-swiftlet.w5.wpsandbox.pro/.

Oxygen 3.1

**Comment by fadlee** [comment]
It seems 404 errors came from different sub domain. 

http://weary-ocelot.w6.wpsandbox.pro/wp-content/cache/oxygen-fix/main-11.css?cache=1551449697&ver=5.3

Regenerating Oxygen CSS cache fix that issue.

**Comment by srikat** [comment]
I still see some problems.

![screenshot](https://d.pr/i/6L0jlO+)

(I did do a hard refresh)

**Comment by fadlee** [comment]
I fixed that issue. The plugin has been updated.

**Comment by srikat** [comment]
All good now. Thanks.
